import * as React from 'react';
import { Table } from 'antd';

export default class DataList extends React.Component {

  constructor () {
    super();
  }

  componentDidMount () {

  }

  render () {
    const columns = [
      {
        'title': '名称',
        'dataIndex': 'name',
        'editable': false,
        'maxLength': 25,
        'type': 'string',
      },
      {
        'title': ' 举办放',
        'dataIndex': 'holder',
        'editable': false,
        'maxLength': null,
        'type': 'string',
      },
      {
        'title': '举办地点',
        'dataIndex': 'location',
        'editable': false,
        'maxLength': null,
        'type': 'string',
      },
      {
        'title': '是否删除',
        'dataIndex': 'del',
        'editable': false,
        'type': 'boolean',
        'render': (text) => {
          return text ? '是' : '否';
        },
      },
    ];
    const dataSource = [
      {
        'authority': null,
        'permission': null,
        'visibility': null,
        'id': 4,
        'name': '北京年度大趴',
        'holder': '北京校友会',
        'location': '北京市 Mee Park智能空间',
        'thumbnail': 'http://static.iqycamp.com/beijing-nhfa2tko.jpg',
        'startTime': 1510977600000,
        'endTime': 1510999200000,
        'status': 3,
        'vipSaleLinkUrl': 'https://www.google.com',
        'guestSaleLinkUrl': 'https://www.baidu.com',
        'linkUrl': 'http://mp.weixin.qq.com/s/H8mUzFiceC5hGMRO6NEFbw',
        'targetUrl': null,
        'linkParam': null,
        'startTimeStr': null,
        'del': false,
      },
      {
        'authority': null,
        'permission': null,
        'visibility': null,
        'id': 5,
        'name': '深圳年度大趴',
        'holder': '深圳校友会',
        'location': '深圳市',
        'thumbnail': 'http://static.iqycamp.com/shenzhen-rs0x1yf4.jpg',
        'startTime': 1513396800000,
        'endTime': 1513418400000,
        'status': 3,
        'vipSaleLinkUrl': 'https://www.google.com',
        'guestSaleLinkUrl': 'https://www.baidu.com',
        'linkUrl': 'http://mp.weixin.qq.com/s/cdZMBQ_FMJnVKT9eLWMYdg',
        'targetUrl': null,
        'linkParam': null,
        'startTimeStr': null,
        'del': false,
      },
      {
        'authority': null,
        'permission': null,
        'visibility': null,
        'id': 6,
        'name': '上海年度大趴',
        'holder': '上海校友会',
        'location': '上海市娄山关路裸心社',
        'thumbnail': 'http://static.iqycamp.com/shanghai-g4kyjwjr.jpg',
        'startTime': 1514606400000,
        'endTime': 1514628000000,
        'status': 3,
        'vipSaleLinkUrl': 'https://www.google.com',
        'guestSaleLinkUrl': 'https://www.baidu.com',
        'linkUrl': 'http://mp.weixin.qq.com/s/B_I_hmXSRaHlANHMYz0I0A',
        'targetUrl': null,
        'linkParam': null,
        'startTimeStr': null,
        'del': false,
      },
      {
        'authority': null,
        'permission': null,
        'visibility': null,
        'id': 7,
        'name': '广州年度大趴',
        'holder': '广州校友会',
        'location': '广州市羊城同创汇',
        'thumbnail': 'http://static.iqycamp.com/activity_04-8zw70d0n.png',
        'startTime': 1515211200000,
        'endTime': 1520330400000,
        'status': 3,
        'vipSaleLinkUrl': 'https://www.google.com',
        'guestSaleLinkUrl': 'https://www.baidu.com',
        'linkUrl': 'http://mp.weixin.qq.com/s/w-rhfUShxfA5HXc5SMpwIw',
        'targetUrl': null,
        'linkParam': null,
        'startTimeStr': null,
        'del': false,
      },
      {
        'authority': null,
        'permission': null,
        'visibility': null,
        'id': 8,
        'name': '杭州年度大趴',
        'holder': '杭州校友会',
        'location': '杭州市艾神家咖啡',
        'thumbnail': 'http://static.iqycamp.com/activity_05-tqpyaanc.png',
        'startTime': 1516420800000,
        'endTime': 1520848800000,
        'status': 3,
        'vipSaleLinkUrl': 'https://www.google.com',
        'guestSaleLinkUrl': 'https://www.baidu.com',
        'linkUrl': 'http://mp.weixin.qq.com/s/BpSeYjpfQ3ACvl8IIr4RTQ',
        'targetUrl': null,
        'linkParam': null,
        'startTimeStr': null,
        'del': false,
      },
      {
        'authority': null,
        'permission': null,
        'visibility': null,
        'id': 9,
        'name': '广州线下工作坊报名',
        'holder': '广州校友会',
        'location': '汉溪长隆地铁站附近',
        'thumbnail': 'http://static.iqycamp.com/activity_01-axd0g40j.png',
        'startTime': 1521957600000,
        'endTime': 1521972000000,
        'status': 2,
        'vipSaleLinkUrl': 'https://shimo.im/docs/GxUuelRV3WsF2mw7',
        'guestSaleLinkUrl': 'https://shimo.im/docs/GxUuelRV3WsF2mw7',
        'linkUrl': 'https://shimo.im/docs/GxUuelRV3WsF2mw7',
        'targetUrl': null,
        'linkParam': null,
        'startTimeStr': null,
        'del': false,
      },
      {
        'authority': null,
        'permission': null,
        'visibility': null,
        'id': 10,
        'name': '杭州线下工作坊报名',
        'holder': '杭州校友会',
        'location': '杭州市滨江区阡陌路459号聚光中心',
        'thumbnail': 'http://static.iqycamp.com/activity_03-fkyzafw2.png',
        'startTime': 1521955800000,
        'endTime': 1521966600000,
        'status': 2,
        'vipSaleLinkUrl': 'https://shimo.im/docs/w7OTYAHokZwtANU0/',
        'guestSaleLinkUrl': 'https://shimo.im/docs/w7OTYAHokZwtANU0/',
        'linkUrl': 'https://shimo.im/docs/w7OTYAHokZwtANU0/',
        'targetUrl': null,
        'linkParam': null,
        'startTimeStr': null,
        'del': false,
      },
      {
        'authority': null,
        'permission': null,
        'visibility': null,
        'id': 11,
        'name': '讲故事：最重要的不是“你说什么”，而是“你怎么说”',
        'holder': '广州校友会',
        'location': '华师地铁站附近（进群后会有详细交通指引）',
        'thumbnail': 'https://static.iqycamp.com/shenzhen-ha25jvad.jpg',
        'startTime': 1526796000000,
        'endTime': 1526983200000,
        'status': 1,
        'vipSaleLinkUrl': 'https://shimo.im/docs/mvPn88LtFMMPTmLT',
        'guestSaleLinkUrl': 'https://shimo.im/docs/eS26wdmOMDoHO9iO',
        'linkUrl': null,
        'targetUrl': null,
        'linkParam': null,
        'startTimeStr': null,
        'del': false,
      },
      {
        'authority': null,
        'permission': null,
        'visibility': null,
        'id': 12,
        'name': '结构化表达线下工作坊',
        'holder': '上海校友会',
        'location': '普陀区曹杨路1626号-Zoo Coffee',
        'thumbnail': 'https://static.iqycamp.com/shanghai-4ca5fdwj.jpg',
        'startTime': 1526968200000,
        'endTime': 1526979600000,
        'status': 1,
        'vipSaleLinkUrl': 'http://www.hdb.com/party/rw6o2.html',
        'guestSaleLinkUrl': 'http://www.hdb.com/party/e2oo2.html',
        'linkUrl': null,
        'targetUrl': null,
        'linkParam': null,
        'startTimeStr': null,
        'del': false,
      },
    ];

    return (
      <div className="table-edit-container">
        <Table columns={columns}
               dataSource={dataSource}
               pagination={{
                 pageSize: 5,
               }}/>
      </div>
    );
  }

}
